<?php

return array (
    'Name' => '您的名字',
    'Password' => '密码',
    'Contact' => '联系电话',
    'Id Num' => '身份证号',
    'Home' => '家庭住址',

    'Pet Type' => '我想领养：',
    'Pet Sex' => '领养性别：',
    'Pet Now' => '现在是否已养动物：',
    'Pet Now Cnt' => '现有动物数量：',
    'Pet Now Type' => '现有动物类型：',
    'Pet Adult' => '是否接受领养成年动物：',
    'Pet Disability' => '是否接受领养残疾动物：',
    'Pet Sterilize' => '是否接受动物绝育：',
    'Sex' => '我的性别：',
    'Job' => '我的职业：',
    'Living' => '住房条件：',
    'Home Idea' => '家人对养动物的意见：',
    'When Pregnant' => '家有孕妇对动物的处理：',
    'Ok Return Visit' => '是否接受协会的回访：',

    'Title' => '标题',
    'Alias' => '简写',
    'Content' => '内容',
    'Desc' => '描述',
    'Create Time' => '创建时间',
    'Update Time' => '更新时间',
    'Delete Time' => '删除时间',
    'Pid' => '父id',
    'PrimaryKey' => '#',
    'Cid' => '#',
    'Content Id' => '#',
    'Uid' => '用户',
    'Status' => '状态',
    'Image' => '图片',
    'Link' => '链接',
);
